#!/bin/bash
# $Id: mblkIP,v 1.2 2019/12/18 10:02:40 fulford Exp fulford $
# $Source: /src/admin/usr/local/etc/RCS/mblkIP,v $
# $Revision: 1.2 $
# Author C W Fulford.
# Copyright 2016 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0793 572 8612
########################################################################
cmd=`basename $0`
max=2000
ver=`echo "$Id: mblkIP,v 1.2 2019/12/18 10:02:40 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
syntax="$cmd  [-d]  [-v] [-m <max instances>|-V]"
while [ $# -gt 0 ] ;do
	case $1 in 
		-d) set -x;debug=0;shift;;
		-h) hostid=$2;shift 2;;			
		-m) max=$2;shift 2;;
		-v) verbose=:;shift;;
		-V) echo "$cmd $Revision: 1.2 $ $Date: 2019/12/18 10:02:40 $"|awk '{print $1,$3,$6}';exit;;  
	esac
done


access=access
cd /src/mailhost/etc/mail
co -q -l access >/dev/null
while read ip count  ;do 
	if [ $count -ge $max ];then
	   string="Connect:$ip ERROR:550 Mail not accepted from this domain"
	   if ! grep -q  "$string" access; then
	  	echo "$string" >> access
	  	[ $verbose ] && echo "$cmd: $ip added to $access"
		restart=0
	   else
	  	[ $verbose ] && echo "$cmd: $ip already included in $access"
	   fi
	fi
done
ci -q access >/dev/null
if [ $restart ];then 
	exit 0
else
	exit 1
fi
