#!/bin/bash
# $Id: mblkIP,v 1.10 2020/03/02 10:17:01 fulford Exp $
# $Source: /src/admin/usr/local/etc/RCS/mblkIP,v $
# $Revision: 1.10 $
# Author C W Fulford.
# Copyright 2016 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0793 572 8612
########################################################################
cmd=`basename $0`
added=0
max=2000
ver=`echo "$Id: mblkIP,v 1.10 2020/03/02 10:17:01 fulford Exp $"|awk '{print $3,$4,$5}'`
syntax="$cmd  [-d]  [-v] [-m <max instances>|-V]"
while [ $# -gt 0 ] ;do
	case $1 in 
		-d) set -x;debug=0;shift;;
		-h) hostid=$2;shift 2;;			
		-m) max=$2;shift 2;;
		-r) restart=0;shift;;
		-v) verbose=:;shift;;
		-V) echo "$cmd $Revision: 1.10 $ $Date: 2020/03/02 10:17:01 $"|awk '{print $1,$3,$6}';exit;;  
	esac
done


access=access
cd /src/mailhost/etc/mail
co -q -l access >/dev/null
while read ip count  ;do 
	if [ $count -ge $max ];then
	   string="Connect:$ip ERROR:550 Mail not accepted from this domain"
	   if ! grep -q  "$string" access; then
	  	echo "$string" >> access
	  	echo "$cmd: $ip added to $access"
		added=`expr $added + 1`
	   else
	  	[ $verbose ] && echo "$cmd: $ip already included in $access"
	   fi
	fi
done
ci -q access >/dev/null
if [ "$restart" -o $added -gt 0 ];then 
	make -s access
	ssh mailhost "/etc/rc.d/rc.sendmail restart"
fi
